### ISSUE TITLE
Working?

### ISSUE THREAD

**Issue by arjun05** [lancenz/Actionstep-API-SDK-PHP#1]
Hi Lance, 

Is this working already?

I have downloaded the source code and I can't connect successfully to actionstep. 

Regards,
Arjun

**Comment by lancenz** [comment]
Hi Arjun, please contact us via our API support email: api@actionstep.com to get started using the API. The SDK is still a work in progress but should be functional, however you still require a valid client_id/client_secret etc to be configured before you can connect to our API which you can get via api@actionstep.com.
